# Import Library

In [ ]:
# prompt: import pandas, numpy, seaborn, visualzation and machine learning

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Import Data

In [ ]:
estate = pd.read_csv('/content/real_estate.csv')
estate

,Date Recorded,List Year,Town,Address,Assessed Value,Sale Amount,Sales Ratio,Property Type,Residential Type,Longitude,Latitude
0,2021-04-14,2020,Ansonia,323 BEAVER ST,133000.0,248400.0,0.5354,Residential,Single Family,-73.06822,41.35014
1,2021-05-26,2020,Ansonia,152 JACKSON ST,110500.0,239900.0,0.4606,Residential,Three Family,NaN,NaN
2,2021-09-13,2020,Ansonia,230 WAKELEE AVE,150500.0,325000.0,0.4630,Commercial,NaN,NaN,NaN
3,2020-12-14,2020,Ansonia,57 PLATT ST,127400.0,202500.0,0.6291,Residential,Two Family,NaN,NaN
4,2021-09-07,2020,Avon,245 NEW ROAD,217640.0,400000.0,0.5441,Residential,Single Family,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
20907,2021-08-25,2020,East Haven,68 BENJAMIN RD,202870.0,399900.0,0.5073,Residential,Single Family,NaN,NaN
20908,2020-12-07,2020,Cornwall,FURNACE BROOK RD,504560.0,559800.0,0.9013,Vacant Land,NaN,NaN,NaN
20909,2021-05-26,2020,Manchester,132 MOUNTAIN ROAD,208000.0,400000.0,0.5200,Residential,Single Family,NaN,NaN
20910,2020-12-09,2020,Manchester,18 HILLCREST ROAD,154100.0,275000.0,0.5603,Residential,Single Family,NaN,NaN
20911,2020-10-01,2020,Bridgeport,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Cleaning Data

In [ ]:
estate.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20912 entries, 0 to 20911
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date Recorded     20912 non-null  object
 1   List Year         20912 non-null  int64
 2   Town              20912 non-null  object
 3   Address           20911 non-null  object
 4   Assessed Value    20911 non-null  float64
 5   Sale Amount       20911 non-null  float64
 6   Sales Ratio       20911 non-null  float64
 7   Property Type     20825 non-null  object
 8   Residential Type  18882 non-null  object
 9   Longitude         9925 non-null   float64
 10  Latitude          9925 non-null   float64
dtypes: float64(5), int64(1), object(5)
memory usage: 1.8+ MB

In [ ]:
estate.describe()

,List Year,Assessed Value,Sale Amount,Sales Ratio,Longitude,Latitude
count,20912.000000,2.091100e+04,2.091100e+04,20911.000000,9925.000000,9925.000000
mean,2019.922772,3.871547e+05,5.393917e+05,0.923444,-72.842730,41.540852
std,1.208902,2.085618e+06,1.333739e+06,7.296897,0.455315,0.266232
min,2001.000000,0.000000e+00,0.000000e+00,0.000000,-75.222600,38.330070
25%,2020.000000,1.046500e+05,1.900000e+05,0.481800,-73.204450,41.345340
50%,2020.000000,1.561000e+05,2.860000e+05,0.557600,-72.805810,41.605630
75%,2020.000000,2.575750e+05,4.650000e+05,0.650100,-72.554860,41.761440
max,2020.000000,6.023185e+07,6.350000e+07,671.889400,-71.792590,42.036000

In [ ]:
estate.isnull().sum()

Date Recorded           0
List Year               0
Town                    0
Address                 1
Assessed Value          1
Sale Amount             1
Sales Ratio             1
Property Type          87
Residential Type     2030
Longitude           10987
Latitude            10987
dtype: int64

In [ ]:
estate.duplicated().sum()

61

In [ ]:
estate.drop_duplicates(inplace=True)

In [ ]:
estate.duplicated().sum()

0

In [ ]:
estate.isna().sum()

Date Recorded           0
List Year               0
Town                    0
Address                 1
Assessed Value          1
Sale Amount             1
Sales Ratio             1
Property Type          87
Residential Type     2025
Longitude           10951
Latitude            10951
dtype: int64

In [ ]:
estate.isnull().sum()

Date Recorded           0
List Year               0
Town                    0
Address                 1
Assessed Value          1
Sale Amount             1
Sales Ratio             1
Property Type          87
Residential Type     2025
Longitude           10951
Latitude            10951
dtype: int64

In [ ]:
print(estate.columns)

Index(['Date Recorded', 'List Year', 'Town', 'Address', 'Assessed Value',
       'Sale Amount', 'Sales Ratio', 'Property Type', 'Residential Type',
       'Longitude', 'Latitude'],
      dtype='object')

In [ ]:
estate['Date Recorded'].dropna(inplace=True)

In [ ]:
estate['Address'] = estate['Address'].str.replace('Street', '')
estate['Address'] = estate['Address'].fillna('Unknown')
estate['Assessed Value'] = estate['Assessed Value'].fillna(estate['Assessed Value'].median())
estate['Residential Type'] = estate['Residential Type'].fillna('Unknown')
estate['Property Type'] = estate['Property Type'].fillna('Unknown')
estate['Longitude'] = estate['Longitude'].fillna('Unknown')
estate['Latitude'] = estate['Latitude'].fillna('Unknown')
estate['Date Recorded'] = estate['Date Recorded'].fillna('Unknown')

In [ ]:
estate

,Date Recorded,List Year,Town,Address,Assessed Value,Sale Amount,Sales Ratio,Property Type,Residential Type,Longitude,Latitude
0,2021-04-14,2020,Ansonia,323 BEAVER ST,133000.0,248400.0,0.5354,Residential,Single Family,-73.06822,41.35014
1,2021-05-26,2020,Ansonia,152 JACKSON ST,110500.0,239900.0,0.4606,Residential,Three Family,Unknown,Unknown
2,2021-09-13,2020,Ansonia,230 WAKELEE AVE,150500.0,325000.0,0.4630,Commercial,Unknown,Unknown,Unknown
3,2020-12-14,2020,Ansonia,57 PLATT ST,127400.0,202500.0,0.6291,Residential,Two Family,Unknown,Unknown
4,2021-09-07,2020,Avon,245 NEW ROAD,217640.0,400000.0,0.5441,Residential,Single Family,Unknown,Unknown
...,...,...,...,...,...,...,...,...,...,...,...
20907,2021-08-25,2020,East Haven,68 BENJAMIN RD,202870.0,399900.0,0.5073,Residential,Single Family,Unknown,Unknown
20908,2020-12-07,2020,Cornwall,FURNACE BROOK RD,504560.0,559800.0,0.9013,Vacant Land,Unknown,Unknown,Unknown
20909,2021-05-26,2020,Manchester,132 MOUNTAIN ROAD,208000.0,400000.0,0.5200,Residential,Single Family,Unknown,Unknown
20910,2020-12-09,2020,Manchester,18 HILLCREST ROAD,154100.0,275000.0,0.5603,Residential,Single Family,Unknown,Unknown
20911,2020-10-01,2020,Bridgeport,Unknown,156015.0,NaN,NaN,Unknown,Unknown,Unknown,Unknown

In [ ]:
estate.isna().sum()

Date Recorded       0
List Year           0
Town                0
Address             0
Assessed Value      0
Sale Amount         1
Sales Ratio         1
Property Type       0
Residential Type    0
Longitude           0
Latitude            0
dtype: int64

In [ ]:
estate.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20851 entries, 0 to 20911
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date Recorded     20851 non-null  object
 1   List Year         20851 non-null  int64
 2   Town              20851 non-null  object
 3   Address           20851 non-null  object
 4   Assessed Value    20851 non-null  float64
 5   Sale Amount       20850 non-null  float64
 6   Sales Ratio       20850 non-null  float64
 7   Property Type     20851 non-null  object
 8   Residential Type  20851 non-null  object
 9   Longitude         20851 non-null  object
 10  Latitude          20851 non-null  object
dtypes: float64(3), int64(1), object(7)
memory usage: 2.4+ MB

# Feature Engineering and Dimensional Reduction

In [ ]:
property_type_counts = estate['Property Type'].value_counts()
print(property_type_counts)

Property Type
Residential       18826
Vacant Land        1045
Commercial          641
Apartments          171
Unknown              87
Industrial           79
Public Utility        2
Name: count, dtype: int64

In [ ]:
# prompt: Tahun berapa rata-rata harga jual properti tertinggi? (Year, Sale Amount)

highest_sale_amount_by_year = estate.groupby('Date Recorded')['Sale Amount'].mean().sort_values(ascending=False).head(1)
year_with_highest_sale_amount = highest_sale_amount_by_year.index[0]
print(f"Year with highest average sale amount: {year_with_highest_sale_amount}")

Year with highest average sale amount: 2021-04-24

In [ ]:
estate = pd.DataFrame(estate)

# Simpan DataFrame ke CSV
estate.to_csv('Estate Fix.csv', index=False)